jobs:
  - script: >
      folder('PetClinic') {
        displayName('PetClinic')
        description('Folder containing PetClinic')
      }

      folder('Samples') {
        displayName('Samples')
        description('Folder containing Samples')
      }

      pipelineJob('Samples/Coverage') {
        definition {
          cps {
            script("""
              pipeline {
                agent any
                stages {
                  stage('Checkout') {
                    steps {
                      git(
                        url: 'https://gitlab.comquent.academy/tn00/petclinic.git',
                        branch: 'musterloesung'
                      )
                    }
                  }
                  stage('Test') {
                    steps {
                      withMaven(maven: 'MVN354') {
                        sh 'mvn test'
                      }
                      junit 'target/surefire-reports/*.xml'
                    }
                  }
                  stage('Coverage') {
                    steps {
                      withMaven(maven: 'MVN354') {
                        sh 'mvn cobertura:cobertura'
                      }
                      recordCoverage(
                        tools: [[parser: 'COBERTURA', pattern: 'target/site/cobertura/coverage.xml']],
                        sourceCodeRetention: 'LAST_BUILD'
                      )
                    }
                  }
                }
              }
            """)
          }
        }
      }

      pipelineJob('Samples/Musterloesung') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  name('origin')
                  url('https://gitlab.comquent.academy/tn00/petclinic.git')
                }                        
                branch('musterloesung')
              }
            }
          }
        }
      }
      
      pipelineJob('Samples/Parallel') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  name('origin')
                  url('https://gitlab.comquent.academy/tn00/petclinic.git')
                }                        
                branch('musterloesung')
              }
            }
            scriptPath('Jenkinsfile_parallel')
          }
        }
      }

      pipelineJob('Samples/Docker') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  name('origin')
                  url('https://gitlab.comquent.academy/tn00/petclinic.git')
                }                        
                branch('docker')
              }
            }
          }
        }
      }
    

