jobs:
  - script: >
      folder('PetClinic') {
        displayName('PetClinic')
        description('Folder containing PetClinic')
      }

      folder('Samples') {
        displayName('Samples')
        description('Folder containing Samples')
      }

      pipelineJob('Samples/Coverage') {
        definition {
          cps {
            script("""
              pipeline {
                agent {
                  docker {
                    image 'maven:3.8.8-eclipse-temurin-8'
                    args '-u root:root'
                  }
                }
                stages {
                  stage('Checkout') {
                    steps {
                      git(
                        url: 'https://github.com/cqNikolaus/petclinic',
                        branch: 'musterloesung'
                      )
                    }
                  }
                  stage('Initial Test & Coverage') {
                    steps {
                      sh 'mvn clean verify'
                      recordCoverage(
                        tools: [[parser: 'JACOCO', pattern: 'target/site/jacoco/jacoco.xml']],
                        sourceCodeRetention: 'LAST_BUILD'
                      )
                    }
                  }
                  
                  stage('Diffblue Generate Tests') {
                    steps {
                      sh 'mvn diffblue:cover'
                    }
                  }
                  
                  stage('New Coverage after Diffblue') {
                    steps {
                      sh 'mvn verify'
                      recordCoverage(
                        tools: [[parser: 'JACOCO', pattern: 'target/site/jacoco/jacoco.xml']],
                        sourceCodeRetention: 'LAST_BUILD'
                      )
                    }
                  }
                }
              }

      pipelineJob('Samples/Musterloesung') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  name('origin')
                  url('https://gitlab.comquent.academy/tn00/petclinic.git')
                }                        
                branch('musterloesung')
              }
            }
          }
        }
      }
      
      pipelineJob('Samples/Parallel') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  name('origin')
                  url('https://gitlab.comquent.academy/tn00/petclinic.git')
                }                        
                branch('musterloesung')
              }
            }
            scriptPath('Jenkinsfile_parallel')
          }
        }
      }

      pipelineJob('Samples/Docker') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  name('origin')
                  url('https://gitlab.comquent.academy/tn00/petclinic.git')
                }                        
                branch('docker')
              }
            }
          }
        }
      }
    

