jobs:
  - script: >
      folder('PetClinic') {
        displayName('PetClinic')
        description('Folder containing PetClinic')
      }

      folder('Samples') {
        displayName('Samples')
        description('Folder containing Samples')
      }

      pipelineJob('Samples/Coverage') {
        definition {
          cps {
            // Dreifach Single-Quotes sorgen für einen reinen String ohne GString-Parsing
            script('''
              pipeline {
                agent {
                  docker {
                    image 'maven:3.8.8-eclipse-temurin-8'
                    args '-u root:root'
                  }
                }
                environment {
                  // Nur statische Variable hier
                  DIFFBLUE_RELEASE_URL = 'https://release.diffblue.com/cli/latest'
                }

                stages {
                  stage('Checkout') {
                    steps {
                      git(
                        url: 'https://github.com/cqNikolaus/petclinic',
                        branch: 'musterloesung'
                      )
                    }
                  }

                  stage('Initial Test & Coverage') {
                    steps {
                      sh 'mvn clean verify'
                      recordCoverage(
                        tools: [[parser: 'JACOCO', pattern: 'target/site/jacoco/jacoco.xml']],
                        sourceCodeRetention: 'LAST_BUILD'
                      )
                    }
                  }

                  stage('Load Credentials') {
                    steps {
                      withCredentials([string(credentialsId: 'diffblue-license-key', variable: 'DIFFBLUE_LICENSE_KEY')]) {
                        sh '''
                          echo "export DIFFBLUE_LICENSE_KEY=\\"$DIFFBLUE_LICENSE_KEY\\"" >> "$WORKSPACE/env.sh"
                        '''.replace('$', '\\$')
                      }
                    }
                  }

                  stage('Setup Diffblue Cover CLI') {
                    steps {
                      sh '''
                        source "$WORKSPACE/env.sh"
                        echo "Download and setup Diffblue Cover CLI..."
                        mkdir -p dcover
                        wget "$DIFFBLUE_RELEASE_URL" -O dcover/dcover.zip -q
                        unzip -o dcover/dcover.zip -d dcover
                        echo "export DIFFBLUE_COVER_LOCATION=dcover/dcover" >> "$WORKSPACE/env.sh"
                      '''.replace('$', '\\$')
                    }
                  }

                  stage('Generate Tests with Diffblue') {
                    steps {
                      sh '''
                        source "$WORKSPACE/env.sh"
                        echo "Run Diffblue Cover to generate tests..."
                        "$DIFFBLUE_COVER_LOCATION" ci activate build validate create
                      '''.replace('$', '\\$')
                    }
                  }

                  stage('New Coverage after Diffblue') {
                    steps {
                      sh 'mvn verify'
                      recordCoverage(
                        tools: [[parser: 'JACOCO', pattern: 'target/site/jacoco/jacoco.xml']],
                        sourceCodeRetention: 'LAST_BUILD'
                      )
                    }
                  }
                }
              }
            ''')
          }
        }
      }

      pipelineJob('Samples/Musterloesung') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  name('origin')
                  url('https://gitlab.comquent.academy/tn00/petclinic.git')
                }
                branch('musterloesung')
              }
            }
          }
        }
      }

      pipelineJob('Samples/Parallel') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  name('origin')
                  url('https://gitlab.comquent.academy/tn00/petclinic.git')
                }
                branch('musterloesung')
              }
            }
            scriptPath('Jenkinsfile_parallel')
          }
        }
      }

      pipelineJob('Samples/Docker') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  name('origin')
                  url('https://gitlab.comquent.academy/tn00/petclinic.git')
                }
                branch('docker')
              }
            }
          }
        }
      }
